import Head from 'next/head';
import Image from 'next/image';

import Layout from '../components/Layout/Layout';
import Layout2 from '../components/Layout/Layout2/Layout2';
import StudentItem from '../components/Main/Student/StudentItem';
import DetailsForm from '../components/Main/Student/DetailsForm';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>School Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout2>
        <h1>Hi Welome to the School Portal</h1>
      </Layout2>
    </div>
  );
}
