import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
import Head from 'next/head';

import { useSession } from 'next-auth/react';
import Layout2 from '../components/Layout/Layout2/Layout2';
import LoadingSpinner from '../components/UI/LoadingSpinner';

import styles from '../styles/Home.module.css';

export default function Home() {
  const session = useSession();
  const router = useRouter();

  useEffect(() => {
    if (session.status === 'unauthenticated') {
      router.push('/auth');
    }
  }, [session]);

  if (session.status === 'loading')
    return (
      <div className='centered'>
        <LoadingSpinner />
      </div>
    );
  return (
    <div className={styles.container}>
      <Head>
        <title>School Management</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout2>
        <div style={{ margin: '20px' }}>
          <h1>Hi Welome to the School Portal</h1>
        </div>
      </Layout2>
    </div>
  );
}
